- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: Please enter your name
  #   private: false # user can see what they are entering
  # - name: WISHES
  #   prompt: Please enter your Wishes
  #   private: false # user can't see what they are entering
  # vars:
  #   PERSON: "Siva from PLAY"
  #   WISHES: "Morning from PLAY"
  tasks:
  - name: check variables
    # vars:
    #   PERSON: "Siva from TASK"
    #   WISHES: "Morning from TASK"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

#1. CMD level arguments
#2. task level (from yaml script)
#3. Files such as variable.yaml
#4. prompt asking for user input from console
#5. play level vars (global variables in playbook)
#6. inventory (inventory file variables)
#7. roles