- name: install nginx
  hosts: web
  become: yes # makes user root user
  tasks:
  - name: install nginx package
    # this installs nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started

