# wap to check user roboshop is exists, if exists skip , if not exists create it
- name: conditions
  hosts: localhost
  tasks:
  - name: check and create roboshop user    # using command module to write shell logics
    ansible.builtin.command: id roboshop
    register: var #this is a variable name
    ignore_errors: true # ansible will not exit when error is encountered
  - name: print variable value
    ansible.builtin.debug:
      msg: "variable output is {{var}}"
  - name: print exit status or return code
    ansible.builtin.debug:
      msg: "status is: {{var.rc}}"


# using when keyword to create a user
  - name: create a user
    ansible.builtin.user:
      name: roboshop
    when: var.rc != 0 #condition