# file for loops
- name: looping over a list of elements
  hosts: localhost
  tasks:
    - name: print the persons from the list
      ansible.builtin.debug:
        msg: "hello {{item}}" # item is default keyword works similar to i in for loop in java
      loop:
        - pk
        - rk
        - kk
        - lk