# installing and uninstalling packages , using name and state for each package in maps of loop
- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall packages
    ansible.builtin.package:
      name: "{{item.name}}" # item is the iterator item.name gets name from loop's map
      state: "{{item.state}}"  # item is the iterator item.state gets package state from loop's map
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'nginx', state: 'present'}